spring:
  application:
    name: bootjar_comment

  r2dbc:
    url: r2dbc:mysql://bootjar-comment-mysql-comment:3306/bootjar_comment
    username: ${username}
    password: ${password}

  liquibase:
    enabled: true
  flyway:
    enabled: true

logging:
  level:
    org.springframework.r2dbc.core: debug

token:
  secret: ${secret}
  expiration: ${exp}

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true